# Spring Data Source 설정 -MySQL DB 접속 정보를 설정

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: "jdbc:h2:mem:library;MODE=MYSQL;NON_KEYWORDS=USER"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format:sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: "jdbc:mariadb://localhost:3306/fruit"
    username: "sonjk"
    password: "1234"
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none #스프링 시작할 때 DB에 있는 테이블을 어떻게 처리할지
    properties:
      hibernate:
        show_sql: true
        format:sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
